# Generated by Django 2.0.3 on 2018-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey> - Page <django.db.models.fields.IntegerField>', max_length=50),
        ),
    ]
