# Generated by Django 2.0.3 on 2018-03-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='name',
        ),
    ]
