# Generated by Django 2.0.3 on 2018-03-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='test_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Page'),
            preserve_default=False,
        ),
    ]
