# Generated by Django 2.0.3 on 2018-03-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180324_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_name',
            new_name='question_text',
        ),
    ]
