# Generated by Django 2.0.3 on 2018-03-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180324_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='test_name',
            new_name='test',
        ),
    ]
