# Generated by Django 2.0.3 on 2018-03-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180324_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Test'),
        ),
    ]
