# Generated by Django 2.0.3 on 2018-03-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
