# Generated by Django 2.0.3 on 2018-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180324_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
