# Generated by Django 2.0.3 on 2018-03-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20180324_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
