# Generated by Django 2.0.3 on 2018-03-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_page_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_order_field', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomWidgetComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('custom_widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.CustomWidget')),
            ],
            options={
                'verbose_name': 'Custom Widget Component',
                'verbose_name_plural': 'Custom Widget Components',
                'ordering': ['widget_order'],
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
