# Generated by Django 2.0.3 on 2018-03-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20180326_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customwidgetcomponent',
            name='custom_widget',
        ),
        migrations.DeleteModel(
            name='CustomWidget',
        ),
        migrations.DeleteModel(
            name='CustomWidgetComponent',
        ),
    ]
