# Generated by Django 2.0.3 on 2018-03-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20180326_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
    ]
