# Generated by Django 2.0.3 on 2018-03-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
    ]
